version: '3'
services:
  spring-petclinic:
    image: arey/springboot-petclinic
    container_name: spring-petclinic
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=hsqldb,prod
